<?php
include("../../etc/config.inc.php");
$uri = "management.phtml";

$man_id = isset($_GET["man_id"]) ? $_GET["man_id"] : 'GGGG';

$THISPAGE = "idep-man"; include("$_BASE/include/header.phtml");
?>
 
<h3>WEPP Management File: <?php echo $man_id; ?></h3>
<pre style="margin-left: 15px;">
<?php
echo file_get_contents("/mnt/a2/wepp/data/managements/${man_id}.man");
?>
</pre>
 
<?php include("../../include/footer.phtml"); ?>
