<?php
  include("../../etc/config.inc.php");
  $THISPAGE = "climate"; include("$_BASE/include/header.phtml");
?>
 

<h2>Climate Data:</h2>

<p>Our daily erosion project runs are based on climate data provided by
the <a href="http://mesonet.agron.iastate.edu">Iowa Environmental Mesonet</a>.
These climate datasets are primarily derived from the National Weather
Service's COOP observer network.

<h3>Applications:</h3>
<ul>
 <li><a href="browse.phtml">Browse</a> climate dataset</li>
</ul>

<p>Note: These climate datasets are currently being worked on and improved.
Some inconsistancies do exist in the archive at this time.

<?php include("$_BASE/include/footer.phtml"); ?>
