<?php
include("../../etc/config.inc.php");
include("../../include/forms.php");
$uri = "erosion.phtml";

$dstr = isset($_GET["dstr"]) ? $_GET["dstr"] : date("m/d/Y", time() - 86400);
$tokens = explode("/", $dstr);
$year = $tokens[2];
$month = $tokens[0];
$day = $tokens[1];

$ts = mktime(0, 0, 0, $month, $day, $year);
$nicedate = strftime("%d %b %Y", $ts);

$oextents = isset($_GET['extents']) ? $_GET['extents'] : "160000, 4450000, 760000, 4850000";
$zoom     = isset($_GET['zoom']) ? $_GET['zoom'] : 0;
$pvar = isset($_GET["pvar"]) ? $_GET['pvar'] : "avg_loss_acre";
$duration = isset($_GET["duration"]) ? $_GET["duration"] : "daily";
$advanced = isset($_GET["advanced"]) ? $_GET["advanced"] : 0;
$metric = isset($_GET["metric"]) ? $_GET["metric"]: "";
$days = isset($_GET["days"]) ? $_GET["days"]: 1;


if ($zoom == 99){
	$oextents = "160000, 4450000, 760000, 4850000";
}

 $imgwidth = 640;
 $imgheight = 480;
 if ( isset($_GET['img_x']) ){
   include("$_BASE/include/click2geo.inc.php");
   $extents = click2geo($oextents, $_GET['img_x'], $_GET['img_y'],
     $_GET['map_width'], $_GET['map_height'], $zoom);
 } else {
   $extents = $oextents;
 }

$keep_vars = Array("pvar" => $pvar, "metric" => $metric, "extents" => $extents,
	"dstr" => $dstr , "days" => $days);

$imgurl = "plot.php?advanced=$advanced&duration=$duration&var=$pvar&extents=$extents&dstr=$dstr&days=$days";

?>

<?php 
 $THISPAGE = "erosion-maps"; 
 $HEADEXTRA = "<script language=\"JavaScript\" src=\"calendar2.js\"></script><!-- Date only with year scrolling -->";
 include("../../include/header.phtml");  ?>

<table><tr><td valign="top">
<strong>Erosion Links:</strong>
<ul>
 <li><a href="/erosion/methodology.phtml">Methodology</a></li>
</ul>

<?php
  $HOF = 'erosion.phtml';

  $side_erosion = 1; include("../../include/side.phtml"); 
?>

</td><td>

<div class="table">
<table>
<tbody></tr>
<td>
<form name="rainfall" action="rainfall.phtml" method="get">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Rainfall Maps">
</form>
</td>
<td>
<form name="erosion" action="erosion.phtml" method="get">
 <input type="hidden" name="pvar" value="avg_runoff_in">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Runoff Maps">
</form>
</td>
<td>
<form name="loss" action="erosion.phtml" method="get">
 <input type="hidden" name="pvar" value="avg_loss_acre">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="month" value="<?php echo $month; ?>">
 <input type="hidden" name="day" value="<?php echo $day; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Soil Erosion Maps">
</form>
</td>
<td>
<form name="sm" action="sm.phtml" method="get">
 <input type="hidden" name="pvar" value="vsm">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Soil Moisture Maps">
</form>
</td>
</tr>
</tbody>
</table>
</div>

<form name="myform" method="GET" action="erosion.phtml">
<div class="table">
 <table>
 <thead>
<tr>
 <th>Duration:</th>
 <th>Day Interval:</th>
 <th>Plot variable:</th>
 <th>Date (mm/dd/yyyy)</th>
 <th></th>
</tr>
 </thead>
 <tbody>
 <tr>
  <td><select name="duration">
<option value="daily" <?php if ($duration == "daily") echo "SELECTED"; ?>>Daily</option>
<option value="monthly" <?php if ($duration == "monthly") echo "SELECTED"; ?>>Monthly</option>
<option value="yearly" <?php if ($duration == "yearly") echo "SELECTED"; ?>>Yearly</option>
</select></td>
<td>
<select name="days">
<?php
 $s ="";
 for ($k=1;$k<94;$k++){
    $s .= "<option value=\"".$k."\" ";
    if ($k == (int)$days){
      $s .= "SELECTED";
    }
    $s .= ">".$k."\n";
  }
  echo $s;
?>
</select>
</td>
<td><?php
echo "<input type=\"hidden\" value=\"yes\" name=\"advanced\">";
echo "<select name=\"pvar\">";
$plotables = Array(
    "min_runoff_in" => "Minimum Daily Runoff [inch]",
	"avg_runoff_in" => "Average Total Runoff [inch]",
	"max_runoff_in" => "Maximum Daily Runoff [inch]",
	"min_runoff_mm" => "Minimum Daily Runoff [mm]",
	"avg_runoff_mm" => "Average Total Runoff [mm]",
	"max_runoff_mm" => "Maximum Daily Runoff [mm]",
	"min_loss_acre" => "Minimum Daily Erosion [tons/acre]",
	"avg_loss_acre" => "Average Total Erosion [tons/acre]",
	"max_loss_acre" => "Maximum Daily Erosion [tons/acre]",
	"min_loss_hectare" => "Minimum Daily Erosion [tons/hectare]",
	"avg_loss_hectare" => "Average Total Erosion [tons/hectare]",
	"max_loss_hectare" => "Maximum Daily Erosion [tons/hectare]",
	"runoff_ratio" => "Runoff Ratio [%]",
	"ve_runoff_in" => "Variance Estimator for Total Runoff [inch]",
	"ve_runoff_mm" => "Variance Estimator for Total Runoff [mm]",
	"ve_loss_acre" => "Variance Estimator for Total Erosion [tons/acre]",
	"ve_loss_hectare" => "Variance Estimatro for Total Erosion [tons/hectare]");

while( list($k,$v) = each($plotables) )
{
  echo "<option value=\"$k\" ";
  if ($pvar == $k) echo "SELECTED";
  echo "> ". $v ."\n"; 
}
 echo "</select>";
?>
</td>
  <td><input type="Text" name="dstr" value="<?php echo $dstr; ?>" maxsize="10" size="12"><a href="javascript:cal.popup();"><img src="img/cal.gif" width="16" height="16" border="0" alt="Click Here to Pick up the date"></a>
</td>
  <td><input type="submit" value="Generate Map"></td>
  </tr>
  </tbody>
  </table>
</div>

<p>
<input type="hidden" name="map_height" value="<?php echo $map->height; ?>">
<input type="hidden" name="map_width" value="<?php echo $map->width; ?>">
<input type="hidden" name="extents" value="<?php echo $map->extent->minx .",".$map->extent->miny .",".$map->extent->maxx .",".$map->extent->maxy ; ?>">
<input type="hidden" name="ul_x" value="<?php echo $map->extent->minx; ?>">
<input type="hidden" name="ul_y" value="<?php echo $map->extent->maxy ; ?>">
<input type="hidden" name="lr_x" value="<?php echo $map->extent->maxx; ?>">
<input type="hidden" name="lr_y" value="<?php echo $map->extent->miny ; ?>">

<input type="hidden" name="zoom" value="1">
<script Language="JavaScript">
 function resetButtons(){
   document.myform.action = 'erosion.phtml';
   document.panButton.src = '../imagenav/button_pan_off.png';
   document.zoominButton.src = '../imagenav/button_zoomin_off.png';
   document.zoomoutButton.src = '../imagenav/button_zoomout_off.png';
   document.queryButton.src = '../imagenav/button_query_off.png';
 }
</script>

<p>Download shapefile options: <a href="/cgi-bin/wepp/idep2shape.py?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>">1 day: <?php echo $nicedate; ?></a> or <a href="/cgi-bin/wepp/idep2shape.py?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=1&monthly=yes">1 month: <?php echo date("M Y", $ts); ?></a>
<?php if ($days > 1){
  echo sprintf(" or <a href=\"/cgi-bin/wepp/idep2shape.py?year=%s&month=%s&day=%s&interval=%s\">%s Day Interval</a>",$year, $month, $day, $days, $days);
} ?>

<p><b>Map Controls:</b>
<img src="../imagenav/button_zoomfull_off.png" name="zoomfullButton" alt="Full Extents"
  onClick="javascript: resetButtons(); document.zoomfullButton.src = '../imagenav/button_zoomfull_on.png'; document.myform.zoom.value = 99; document.myform.submit();">
<img src="../imagenav/button_zoomin_off.png" name="zoominButton" alt="Zoom In"
  onClick="javascript: resetButtons(); document.zoominButton.src = '../imagenav/button_zoomin_on.png'; document.myform.zoom.value = -2;">
<img src="../imagenav/button_pan_on.png" name="panButton" alt="Pan"
  onClick="javascript: resetButtons(); document.panButton.src = '../imagenav/button_pan_on.png'; document.myform.zoom.value = 1;">
<img src="../imagenav/button_zoomout_off.png" name="zoomoutButton" alt="Zoom Out"
  onClick="javascript: resetButtons(); document.zoomoutButton.src = '../imagenav/button_zoomout_on.png'; document.myform.zoom.value = 2;">
<img src="../imagenav/button_query_off.png" name="queryButton" alt="Query"
  onClick="javascript: resetButtons(); document.queryButton.src = '../imagenav/button_query_on.png'; document.myform.action = 'click.php';">

<a href="<?php echo $imgurl; ?>&dl=yes">Save Image</a>
<p><input type="image" name="img" src="<?php echo $imgurl; ?>" border="1">
</form>
<script language="JavaScript">
<!-- // as
var cal = new calendar2(document.forms['myform'].elements['dstr']);
cal.year_scroll = true;
cal.time_comp = false;
//-->
</script>

</td></tr></table>

<?php include("../../include/footer.phtml"); ?>
