<?php
include("../../etc/config.inc.php");
include("../../include/forms.php");
$uri = "rainfall.phtml";
$advanced = "1";

$dstr = isset($_GET["dstr"]) ? $_GET["dstr"] : date("m/d/Y", time() -100000);
$metric = isset($_GET["metric"]) ? $_GET["metric"]: "";
$tokens = explode("/", $dstr);
$year = $tokens[2];
$month = $tokens[0];
$day = $tokens[1];


$duration = isset($_GET['duration'])? $_GET["duration"] : "daily";
$oextents = isset($_GET['extents']) ? $_GET['extents'] : "160000, 4450000, 760000, 4850000";
$zoom     = isset($_GET['zoom']) ? $_GET['zoom'] : 0;
$pvar = isset($_GET['pvar']) ? $_GET['pvar'] : "rainfall_in";
$days = isset($_GET["days"]) ? $_GET["days"]: 1;

if ($zoom == 99) {
 $oextents = "160000, 4450000, 760000, 4850000";
}

 $imgwidth = 640;
 $imgheight = 480;
 if ( isset($_GET['img_x']) ){
   include("../../include/click2geo.inc.php");
   $extents = click2geo($oextents, $_GET['img_x'], $_GET['img_y'],
     $_GET['map_width'], $_GET['map_height'], $zoom);
 } else {
   $extents = $oextents;
 }

$keep_vars = Array("pvar" => $pvar, "metric" => $metric, "extents" => $extents,
  "duration" => $duration, "dstr" => $dstr, "days" => $days);


$ts = mktime(0, 0, 0, $month, $day, $year);
$nicedate = strftime("%d %b %Y", $ts);


$erosionURL = strftime('erosion.phtml?dstr=%m/%d/%Y' , $ts);

$imgurl = "plot.php?duration=$duration&var=$pvar&extents=$extents&dstr=$dstr&days=$days";

?>
<?php 
 $THISPAGE = "rainfall"; 
 $HEADEXTRA = "<script language=\"JavaScript\" src=\"calendar2.js\"></script><!-- Date only with year scrolling -->";
 include("../../include/header.phtml"); 
?>

<table><tr><td valign="top">
<strong>Rainfall Links:</strong>
<ul>
 <li><a href="../rainfall/methodology.phtml">Methodology</a></li>
</ul>

<?php
  $HOF = 'rainfall.phtml';

  $side_rainfall = 1; include("../../include/side.phtml");
?></td><td>
                                                                                

<div class="table">
<table>
<tbody></tr>
<td>
<form name="rainfall" action="rainfall.phtml" method="get">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Rainfall Maps">
</form>
</td>
<td>
<form name="erosion" action="erosion.phtml" method="get">
 <input type="hidden" name="pvar" value="avg_runoff_in">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Runoff Maps">
</form>
</td>
<td>
<form name="loss" action="erosion.phtml" method="get">
 <input type="hidden" name="pvar" value="avg_loss_acre">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Soil Loss Maps">
</form>
</td>
<td>
<form name="sm" action="sm.phtml" method="get">
 <input type="hidden" name="pvar" value="vsm">
 <input type="hidden" name="dstr" value="<?php echo $dstr; ?>">
 <input type="hidden" name="advanced" value="<?php echo $advanced; ?>">
 <input type="hidden" name="extents" value="<?php echo $extents; ?>">
 <input type="submit" value="Soil Moisture Maps">
</form>
</td>
</tr>
</tbody>
</table>
</div>

<form method="GET" action="rainfall.phtml" name="myform">

<div class="table">
<table>
<thead>
<tr>
<th>Time Period</th>
<th>Day Interval</th>
<th>Plot Variable</th>
<th>Date (mm/dd/yyyy)</th>
</tr>
</thead>
<tbody>
<tr><td>
 <select name="duration">
   <option value="daily" <?php if ($duration == "daily") echo "SELECTED"; ?>>Daily
   <option value="monthly" <?php if ($duration == "monthly") echo "SELECTED"; ?>>Monthly
   <option value="yearly" <?php if ($duration == "yearly") echo "SELECTED"; ?>>Yearly
 </select>
</td>
<td>
<select name="days">
<?php
 $s ="";
 for ($k=1;$k<63;$k++){
    $s .= "<option value=\"".$k."\" ";
    if ($k == (int)$days){
      $s .= "SELECTED";
    }
    $s .= ">".$k."\n";
  }
  echo $s;
?>
</select>
</td>
<td>
 <select name="pvar">
	<option value="rainfall_in" <?php if ($pvar == "rainfall_in") echo "SELECTED"; ?>>Rainfall Total [in]
	<option value="rainfall_mm" <?php if ($pvar == "rainfall_mm") echo "SELECTED"; ?>>Rainfall Total [mm]
	<option value="peak_15min_in" <?php if ($pvar == "peak_15min_in") echo "SELECTED"; ?>>Peak Intensity [in/hr]
	<option value="peak_15min_mm" <?php if ($pvar == "peak_15min_mm") echo "SELECTED"; ?>>Peak Intensity [mm/hr]
	<option value="time_" <?php if ($pvar == "time_") echo "SELECTED"; ?>>Rainfall Time
 </select>
</td>
<td><input type="Text" name="dstr" value="<?php echo $dstr; ?>" maxsize="10" size="12"><a href="javascript:cal.popup();"><img src="img/cal.gif" width="16" height="16" border="0" alt="Click Here to Pick up the date"></a>
</td>

</tr>
</tbody>
</table>
</div>

<br /><input type="submit" value="Generate Map">


<p>
<input type="hidden" name="map_height" value="<?php echo $map->height; ?>">
<input type="hidden" name="map_width" value="<?php echo $map->width; ?>">
<input type="hidden" name="ul_x" value="<?php echo $map->extent->minx; ?>">
<input type="hidden" name="ul_y" value="<?php echo $map->extent->maxy ; ?>">
<input type="hidden" name="lr_x" value="<?php echo $map->extent->maxx; ?>">
<input type="hidden" name="lr_y" value="<?php echo $map->extent->miny ; ?>">
<input type="hidden" name="extents" value="<?php echo $map->extent->minx .",".$map->extent->miny .",".$map->extent->maxx .",".$map->extent->maxy ; ?>">
<input type="hidden" name="zoom" value="1">
<script Language="JavaScript">
 function resetButtons(){
   document.myform.action = 'rainfall.phtml';
   document.panButton.src = '../imagenav/button_pan_off.png';
   document.zoominButton.src = '../imagenav/button_zoomin_off.png';
   document.zoomoutButton.src = '../imagenav/button_zoomout_off.png';
   document.queryButton.src = '../imagenav/button_query_off.png';
 }
</script>
<b>Map Controls:</b>
<img src="../imagenav/button_zoomfull_off.png" name="zoomfullButton" alt="Full Extents"
  onClick="javascript: resetButtons(); document.zoomfullButton.src = '../imagenav/button_zoomfull_on.png'; document.myform.zoom.value = 99; document.myform.submit();">
<img src="../imagenav/button_zoomin_off.png" name="zoominButton" alt="Zoom In"
  onClick="javascript: resetButtons(); document.zoominButton.src = '../imagenav/button_zoomin_on.png'; document.myform.zoom.value = -2;">
<img src="../imagenav/button_pan_on.png" name="panButton" alt="Pan"
  onClick="javascript: resetButtons(); document.panButton.src = '../imagenav/button_pan_on.png'; document.myform.zoom.value = 1;">
<img src="../imagenav/button_zoomout_off.png" name="zoomoutButton" alt="Zoom Out"
  onClick="javascript: resetButtons(); document.zoomoutButton.src = '../imagenav/button_zoomout_on.png'; document.myform.zoom.value = 2;">
<img src="../imagenav/button_query_off.png" name="queryButton" alt="Query"
  onClick="javascript: resetButtons(); document.queryButton.src = '../imagenav/button_query_on.png'; document.myform.action = 'click.php';">

<a href="<?php echo $imgurl; ?>&dl=yes">Save Image</a>

<p><div style="width: 650px;"><input type="image" name="img" src="<?php echo $imgurl; ?>" border="1" height="480" width="640"></div>
</form>
<script language="JavaScript">
<!-- // as
var cal = new calendar2(document.forms['myform'].elements['dstr']);
cal.year_scroll = true;
cal.time_comp = false;
//-->
</script>

</td></tr></table>

<?php include("../../include/footer.phtml"); ?>
