<?php
  include("../etc/config.inc.php");
  $THISPAGE = "idep-about"; include("../include/header.phtml");
?>
<div class="gutter">
<h2>Project Info:</h2>

<p>The Iowa Daily Erosion Project resulted from discussions between Rick Cruse, and Iowa State Professor of Soil Management and John Laflen, a retired USDA Agricultural Research Service Agricultural Engineer, on ways to bring increased attention to the problem of excess soil erosion. Soil erosion by water only occurs during storms that produce runoff and is thus a temporally and spatially dynamic process. To help visualize the process, Drs. Cruse and Laflen came up with the The Iowa Daily Erosion Project, a daily simulation of the erosion process on nearly 20,000 hillslopes across the state of Iowa. The project was implemented through the collaboration of numerous scientists from Iowa State University, the University of Iowa, the USDA ARS National Soil Erosion Research Laboratory and National Laboratory for Agriculture and the Environment. The process was peer reviewed and published in the January/February 2006 issue of the Journal of Soil and Water Conservation.

<p>Details about the methodology used to derive the estimates are contained on the erosion and rainfall pages. We have been working to update the methodology used to populate the soils, management, and topography databases using remotely sensed data to enable higher resolution and more current management data than the township level, nineteen year old NRI data allow. We have already developed methods for determining crop rotations and tillage practices and are working on processing the state LiDAR data to accurately determine slope and length. These methods could also extend the Daily Erosion Project beyond the boundaries of Iowa.
</div>


<?php include("../include/footer.phtml"); ?>
