<?php
  include("../etc/config.inc.php");
  $THISPAGE = "contact"; include("../include/header.phtml");
?>
 
 
<h2>Project Contacts:</h2>

<p><b>Principal Investigator:</b> Dr Rick Cruse  
<br /><i>Email:</i>  <a href="mailto:rmc@iastate.edu">rmc@iastate.edu</a></p>

<p><b>Technical/Webmaster:</b> Daryl Herzmann
<br /><i>Email:</i> <a href="mailto:akrherz@iastate.edu">akrherz@iastate.edu</a></p>


<?php include("../include/footer.phtml"); ?>
