<table bgcolor="#3366cc" width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td><font color="#ffffff"><h2> &nbsp; Iowa Soil Erosion Project</h2></font></td>
</tr>
</table>
<table width="100%" id="navBar" border="0" cellpadding="4" cellspacing="0">
<tr valign="top">
	<td id="navLinks" width="100%">
		<a href="http://wepp.mesonet.agron.iastate.edu/">Home</a>  
		<img src="/images/nav_sep.gif" alt="" align="absmiddle" hspace="1" width="1" height="17"> 
		<a href="/about.phtml">Project&nbsp;Info</a> 
		<img src="/images/nav_sep.gif" alt="" align="absmiddle" hspace="1" width="1" height="17"> 
		<a href="/contact.phtml">Contact&nbsp;Us</a> 

	</td>
</tr>
</table>
<table><tr><td width="5"></td><td>
