<?php 
  include("../etc/config.inc.php"); 
  $HEADEXTRA = "<script language=\"JavaScript\" src=\"calendar2.js\"></script>";
  $THISPAGE = "idep-homepage"; include("$_BASE/include/header.phtml"); 
  include("$_BASE/include/forms.php"); 
/*  include("../include/side.phtml"); */
  $today = mktime(0,0,0, date("m"), date("d"), date("Y") );
  $astart = mktime(0,0,0, 1, 1, 2002);

$dstr = isset($_GET["dstr"]) ? $_GET["dstr"] : date("m/d/Y", time() - 86400);
$tokens = explode("/", $dstr);
$year = $tokens[2];
$month = $tokens[0];
$day = $tokens[1];

  $ts = mktime(0,0,0,$month, $day, $year);
  if ($ts >= $today)
  {
    $ts = $today - 3*3600; /* Yesterday */
  }
  if ($ts < $astart)
  {
    $ts = $astart; 
  }
?>

<!-- content BEGIN -->
<div class="gutter">

<p>Welcome to the homepage for the <strong>The Iowa Daily Erosion Project</strong>. 
Our project is a collaboration of scientists at 
<a href="http://www.iastate.edu">Iowa State University</a>, 
<a href="http://topsoil.nserl.purdue.edu/nserlweb/">National Soil Erosion Research Lab</a>, 
<a href="http://www.ars.usda.gov/main/site_main.htm?modecode=36-25-15-00">National
Laboratory for Agriculture and the Environment</a>, 
and <a href="http://www.uiowa.edu">The University of Iowa</a>.  
Our aim is to produce daily estimates of rainfall, runoff, and soil erosion 
for the state of Iowa.  Our work is sponsored by 
<a href="http://www.agron.iastate.edu">Department of Agronomy's</a> 
<a href="http://www.agron.iastate.edu/initiatives/default.html">Path to the Future</a> 
endowment.</p>

<p class="notify-msg">Our project has a display inside the ISU building at the
Farm Progress Show (28-30 August 2012)!  Be sure to stop by to see us, <a href="nextgen.php">here</a>
is the kiosk style display being shown off at the show.</p>

<h1>Map Quickview:</h1>

<form method="GET" action="index.phtml" name="myform">
<div class="table">
<table>
<thead>
<tr>
<th>Prev Day</th>
<th>Next Day</th>
<th>Date (mm/dd/yyyy)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="index.phtml?dstr=<?php echo strftime("%m/%d/%Y", $ts - 86400); ?>"><?php echo date("d M Y", $ts - 86400); ?></a></td>
<td><a href="index.phtml?dstr=<?php echo strftime("%m/%d/%Y", $ts + 92000); ?>"><?php echo date("d M Y", $ts + 92000); ?></a></td>
<td><input type="Text" name="dstr" value="<?php echo $dstr; ?>" maxsize="10" size="12"><a href="javascript:cal.popup();"><img src="img/cal.gif" width="16" height="16" border="0" alt="Click Here to Pick up the date"></a></td>
<td><input type="submit" value="View Maps"></td>
</tr>
</tbody>
</table>
</div>
</form>
<script language="JavaScript">
<!-- // as
var cal = new calendar2(document.forms['myform'].elements['dstr']);
cal.year_scroll = true;
cal.time_comp = false;
//-->
</script>


<div class="table">
<table>
<tr><th>Rainfall</th><th>Runoff</th></tr>
<tr>
 <td><a href="GIS/rainfall.phtml?option=daily&pvar=rainfall_in&dstr=<?php echo strftime("%m/%d/%Y", $ts); ?>"><img src="http://wepp.mesonet.agron.iastate.edu/static/<?php echo strftime("%Y/%m/%d", $ts); ?>_daily_rainfall_in.png"></a></td>
 <td><a href="GIS/erosion.phtml?pvar=avg_runoff_in&dstr=<?php echo strftime("%m/%d/%Y", $ts); ?>"><img src="http://wepp.mesonet.agron.iastate.edu/static/<?php echo strftime("%Y/%m/%d", $ts); ?>_daily_avg_runoff_in.png"></a></td>
</tr>
<tr><th>Soil Erosion</th><th>Soil Moisture</th></tr>
<tr>
 <td><a href="GIS/erosion.phtml?pvar=avg_loss_acre&dstr=<?php echo strftime("%m/%d/%Y", $ts); ?>"><img src="http://wepp.mesonet.agron.iastate.edu/static/<?php echo strftime("%Y/%m/%d", $ts); ?>_daily_avg_loss_acre.png"></a></td>
 <td><a href="GIS/sm.phtml?pvar=vsm&dstr=<?php echo strftime("%m/%d/%Y", $ts); ?>"><img src="http://wepp.mesonet.agron.iastate.edu/static/<?php echo strftime("%Y/%m/%d", $ts); ?>_daily_vsm.png"></a></td>
</tr>
</table>
</div>

<br clear="all" \>
<h1>Mailing List:</h1>
<ul>
<li><a href="http://mesonet.agron.iastate.edu/mailman/listinfo/wepp">Email List interface</a></li>
<li><a href="http://mesonet.agron.iastate.edu/mailman/private/wepp/">List archives (not-public)</a></li>
</ul>

</div>

<?php include("../include/footer.phtml"); ?>
