<?php
  include("../etc/config.inc.php");
  include("../include/header.phtml");
  include("../include/side.phtml");
?>
 
<!-- content BEGIN -->
<div id="wepp-middle-two">
<div id="wepp-content">
<div id="page-main">
 

<h2>TODO List:</h2>

<p>Listing of TODO items for our project.  If you have additions or suggestions, please don't hesitate to <a href="contact.phtml">contact us</a>.</p>

<div class="table">
<table>
<colgroup>
 <col align="left">
 <col align="left">

 <col align="left">
</colgroup>
<thead><tr>
 <td>Item:</td>
 <td>Added:</td>
 <td>Completed:</td>
</tr></thead>
<tbody>
<tr>
 <td>Fix post-processing script to account for zeros in stat generation.</td>
 <td>22 Feb 2004</td>
 <td></td>
</tr>

<tr>
 <td>Web interface to show management/rotation details.</td>
 <td>22 Feb 2004</td>
 <td></td>
</tr>

<tr>
 <td>Interface to build loops of 15 minute rainfall estimates.</td>
 <td>22 Feb 2004</td>
 <td></td>
</tr>

<tr>
 <td>Rainfall data mapped to hydrologic basins.</td>
 <td>11 Mar 2004</td>
 <td></td></tr>

<tr>
 <td>Formalize support for importing data into COTS GIS</td>
 <td>11 Mar 2004</td>
 <td></td></tr>

</tbody>
</table></div>

</div>


</div></div></div>

<?php include("../include/footer.phtml"); ?>
