<?php
 /** Rainfall Homepage */
 include("../../etc/config.inc.php");
 
 include("../../include/header.phtml");
 $side_rainfall = 1; include("../../include/side.phtml");
?>
 
<!-- content BEGIN -->
<div id="wepp-middle-two">
<div id="wepp-content">
<div id="page-main">

<h1>Rainfall Estimates:</h1>

<p>The most important variable in estimating erosion is rainfall.  Our 
project has made attempts to produce a temporally (15 minute) 
and spatially (16 km^2) fine 
depiction of rainfall over the state of Iowa.</p>

<p><h3><a href="../GIS/rainfall.phtml">View Maps:</a></h3></p>

<p>View maps of daily and monthly rainfall accumulation since 1 January 2002.</p>

<p><h3><a href="methodology.phtml">Rainfall Methodology</a></h3></p>

<p>Documentation on how we produce our estimates.</p>

</div></div></div>
<?php include("../../include/footer.phtml"); ?>
