			<div class="clear"></div>
		</div>
	</div>
	<div class="fwrapper grids-24">
		<div class="grids-24" id="footer">
			<div class="grid-3 first">
				<a class="nameplate" href="/"><img alt="Iowa State University" src="/img/sprite.png"></a>
			</div>
			<div class="grid-21 last">
				<p>
					2104 Agronomy Hall, (515) 294-1360, <script>document.write('<a href="mailto:'+ ["agron", "iastate.edu"].join('@') +'">'+ ["agron", "iastate.edu"].join('@') +'</a>')</script><noscript>agron (at) iastate (dot) edu</noscript>.
				</p>
				<p>
					Copyright &copy; 1995-2012, Iowa State University of Science and Technology.
					All rights reserved. 
				</p>
			</div>
		</div>
	</div>
</body>
</html>