<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>Iowa Daily Erosion Project</title>
<link rel="stylesheet" type="text/css" href="<?php echo $_WEBBASE; ?>/css/content.css" />
<link rel="icon" href="<?php echo $_WEBBASE; ?>images/icon.gif" type="image/gif">
<script language="JavaScript" type="text/javascript">
window.name = "content";
function new_window(url) {
 link = window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=810,height=810");
} 
</script>
<?php echo $HEADEXTRA; ?>
</head>

<body>
<?php include("$_BASE/include/webring.html"); ?>
<div id="wepp-header">
 <div id="wepp-header-logo"><img src="<?php echo $_WEBBASE; ?>/images/erosion.gif"></div>
 <h1>Iowa Daily Erosion Project</h1>
 <div id="wepp-header-rlogo"><a href="http://www.agron.iastate.edu/initiatives/default.html"><img src="<?php echo $_WEBBASE; ?>/images/ptfmark.gif"></a></div>
</div>

<div id="mainNavOuter">
<div id="mainNav">
<div id="mainNavInner">

 <ul>
  <li id="mainFirst<?php if ($THISPAGE == "homepage") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/index.phtml">Homepage</a></li>
  <li id="main<?php if ($THISPAGE == "erosion") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/GIS/erosion.phtml">Erosion</a></li>
  <li id="main<?php if ($THISPAGE == "rainfall") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/GIS/rainfall.phtml">Rainfall</a></li>
  <li id="main<?php if ($THISPAGE == "climate") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/climate/index.phtml">Climate</a></li>
  <li id="main<?php if ($THISPAGE == "township") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/township/index.phtml">By Township</a></li>
  <li id="main<?php if ($THISPAGE == "info") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/about.phtml">Project Info</a></li>
  <li id="mainLast<?php if ($THISPAGE == "contact") echo "-active"; ?>"><a href="<?php echo $_WEBBASE; ?>/contact.phtml">Contact Us</a></li>
 </ul>

</div>
</div>
</div>
