<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title><?php echo isset($TITLE) ? $TITLE: "Iowa Daily Erosion Project"; ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $_WEBBASE; ?>/css/content.css" />
<link rel="icon" href="<?php echo $_WEBBASE; ?>images/icon.gif" type="image/gif">
<script language="JavaScript" type="text/javascript">
window.name = "content";
function new_window(url) {
 link = window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=810,height=810");
} 
</script>
<?php if (isset($HEADEXTRA)) echo $HEADEXTRA; ?>
</head>

<body>
<?php include("$_BASE/include/webring.html"); ?>
<div id="wepp-header">
 <div id="wepp-header-logo"><img src="<?php echo $_WEBBASE; ?>/images/erosion.gif"></div>
 <h1>Iowa Daily Erosion Project</h1>
 <div id="wepp-header-rlogo"><a href="http://www.agron.iastate.edu/initiatives/default.html"><img src="<?php echo $_WEBBASE; ?>/images/ptfmark.gif"></a></div>
</div>

<?php

$_pages = Array(
 "idep" => Array(
    "base" => Array("title" => "IDEP", "url" => "/index.phtml"),
    "homepage" => Array("title" => "Homepage", "url" => "/"),
    "about" => Array("title" => "About", "url" => "/about.phtml"),
    "contact" => Array("title" => "Contact Us", "url" => "/contact.phtml"),
    "man" => Array("title" => "Managements", "url" => "/meta/management.phtml"),
 ),
 "erosion" => Array(
    "base" => Array("title" => "Erosion", "url" => "/GIS/erosion.phtml"),
    "maps" => Array("title" => "Maps", "url" => "/GIS/erosion.phtml"),
    "methodology" => Array("title" => "Methodology", "url" => "/erosion/methodology.phtml"),
 ),
 "rainfall" => Array(
    "base" => Array("title" => "Rainfall", "url" => "/GIS/rainfall.phtml"),
    "maps" => Array("title" => "Maps", "url" => "/GIS/rainfall.phtml"),
    "methodology" => Array("title" => "Methodology", "url" => "/rainfall/methodology.phtml"),
 ),
 "sm" => Array(
    "base" => Array("title" => "Soil Moisture", "url" => "/GIS/sm.phtml"),
    "map" => Array("title" => "Maps", "url" => "/GIS/sm.phtml"),
 ),
 "climate" => Array(
    "base" => Array("title" => "Climate", "url" => "/climate/"),
    "browse" => Array("title" => "Browse", "url" => "/climate/browse.phtml"),
 ),
 "township" => Array(
    "base" => Array("title" => "By Township", "url" => "/township/"),
    "map" => Array("title" => "Select Map", "url" => "/township/"),
    "daily" => Array("title" => "Daily Result", "url" => "/township/byday.phtml"),
    "yearly" => Array("title" => "Yearly Result", "url" => "/township/byyear.phtml"),
  ),
);

$THISPAGE = isset($THISPAGE) ? $THISPAGE : "networks-base";
$ar = split("-", $THISPAGE);
if (sizeof($ar) == 1) $ar[1] = "";
echo "<div id=\"iem_nav\"><ul>\n";
$b = "";
while( list($idx, $page) = each($_pages) )
{
  echo sprintf("<li%s><a href=\"%s\">%s</a></li>", 
      ($ar[0] == $idx) ? " class=\"selected\"" : " ",
      $_WEBBASE . $page["base"]["url"], $page["base"]["title"]);
  if ($ar[0] == $idx)
  {
    $b .= "<div id=\"iem_subnav\"><ul>\n";
    while( list($idx2, $page2) = each($page) )
    {
       if ($idx2 == "base") continue;
       $b .= sprintf("<li%s><a href=\"%s\">%s</a></li>", 
         ($ar[1] == $idx2) ? " class=\"selected\"" : " ",
          $_WEBBASE . $page[$idx2]["url"], 
     ($ar[1] == $idx2) ? "[ ". $page[$idx2]["title"] ." ]": $page[$idx2]["title"
] );
    }
    $b .= "</ul></div>\n";
  }
}
echo "</ul></div> $b";
?>
<br clear="all" />
