
<?php if (isset($request_twp)){ ?>
 <div class="wepp-side-left-content">
   <b>Township:</b>
   <form name="settwp" action="<?php echo $uri; ?>" method="GET">
<?php while( list($kvarname, $kvar) = @each($keep_vars) ) {
 echo "<input type=\"hidden\" name=\"$kvarname\" value=\"$kvar\">\n";
} ?>
   <input name="twp" type="text" size="10" value="<?php echo $twp; ?>">
   <input type="submit" value="Set"></form>
 </div>
<?php } ?>


<?php if (isset($request_date)){ 
  include("forms.php"); ?>
 <div class="wepp-side-left-content">
   <b>Set Date:</b>
   <form name="setdate" action="<?php echo $uri; ?>" method="GET">
   <?php 
    while( list($kvarname, $kvar) = @each($keep_vars) ) {
      echo "<input type=\"hidden\" name=\"$kvarname\" value=\"$kvar\">\n";
    }
     echo "Year:<br />". yearSelect(2002, $year, "year"); 
     echo "<br />Month:<br />". monthSelect($month, "month"); 
     echo "<br />Day:<br />". daySelect($day, "day"); 
   ?>
   <input type="submit" value="Set"></form>
 </div>
<?php } ?>

<?php if (isset($extents)){

if (! extension_loaded('MapScript') ) dl($mapscript);
$map = ms_newMapObj("$_BASE/data/gis/map/wepp.map");

/* Set Extents */
$arExtents = explode(",", $extents);
$map->setextent($arExtents[0], $arExtents[1], $arExtents[2], $arExtents[3]);

$ref = $map->drawReferenceMap();
$refurl = $ref->saveWebImage();

/* We need to do some math to figure out our zoom scale */
$refExtents = Array(154000,4420187.5,766000,4879812.5);
$arExtents = explode(",", $extents);
$refWidth = $refExtents[2] - $refExtents[0];
$curWidth = $arExtents[2] - $arExtents[0];
$zoomscale = 0.0 - ($refWidth / $curWidth);
//echo "<br/> ". $zoomscale;
//echo "<br/> ". $curWidth;
//echo "<br/> ". $refWidth;
?>
<div class="wepp-side-left-content">
<b>Reference Map:</b><br /><i>Click on this map to recenter.</i><br />
<form name="refform" method="GET">
<?php
  while( list($kvarname, $kvar) = @each($keep_vars) ) {
      echo "<input type=\"hidden\" name=\"$kvarname\" value=\"$kvar\">\n";
    }
?>
<input type="hidden" name="extents" value="154000,4420187.5,766000,4879812.5">
<input type="hidden" name="zoom" value="<?php echo $zoomscale; ?>">
<input type="hidden" name="map_height" value="105">
<input type="hidden" name="map_width" value="140">
<br><input type="image" name="img" src="<?php echo $refurl; ?>">
</form>
</div>
<?php } ?>

<?php if (isset($HOF)) { ?>
<div class="wepp-side-left-content">
<?php echo $HOF; ?>
</div>
<?php } ?>

</div>
