<?php
 /** Erosion Homepage */
 include("../../etc/config.inc.php");
 
 include("../../include/header.phtml");
 $side_erosion = 1; include("../../include/side.phtml");
?>
 
<!-- content BEGIN -->
<div id="wepp-middle-two">
<div id="wepp-content">
<div id="page-main">

<h1>Erosion Estimates:</h1>

<p>Our project aims to provide estimates of daily soil erosion in near real
time.  A daily automated process begins at 3:30 AM with the goal of producing
erosion estimates for the previous day based on our <a href="../rainfall">rainfall estimates</a>.  With over 90,000 potential runs in our modeling effort, this
process can take into the mid afternoon to complete.  We are currently working
on speeding the processing up, so that yesterday's erosion estimates are 
completed by mid morning.</p>

<p><h3><a href="../GIS/erosion.phtml">View Maps</a></h3></p>

<p>View maps of daily erosion estimates dating back to 1 Jan 2002.</p>

</div></div></div>
<?php include("../../include/footer.phtml"); ?>
