ucnids:
	gcc -o ucnids -lz ucnids.c
	mv ucnids ../bin/

read_raster_RLE:
	gcc -o read_raster_RLE read_raster_RLE.c
	mv read_raster_RLE ../bin/

create15minutes:
	gcc -o create15minutes -lm create15minutes.c
	mv create15minutes ../bin/

createHRAP:
	gcc -o createHRAP createHRAP.c
	mv createHRAP ../bin/

readST4:
	gcc -o readST4 readST4.c
	mv readST4 ../bin/

readST4-old:
	gcc -o readST4-old readST4-old.c
	mv readST4-old ../bin/

killbigvalue:
	gcc -o killbigvalue killbigvalue.c
	mv killbigvalue ../bin/

combine:
	gcc -o combine combine.c
	mv combine ../bin/
